# Generated by Django 4.2.11 on 2024-03-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(
                choices=[
                    ("farsi", "Farsi"),
                    ("english", "English"),
                    ("spanish", "Spanish"),
                    ("german", "German"),
                ],
                help_text="Select a language from this dropdown",
                max_length=100,
                null=True,
            ),
        ),
    ]
